DROP TABLE NOTIFICATION;
DROP TABLE expense;
DROP TABLE user_group;
DROP TABLE application_user;
DROP TABLE expense_group;
DROP TABLE hibernate_sequence;
DROP TABLE notification;
DROP TABLE flyway_schema_history;
DROP TABLE image;
